"""
Stage 6, File 1: Summary Deep Agent
====================================
CONCEPT: Using Deep Agents harness for meeting summarization.

Deep Agents provide built-in capabilities:
- Task planning with todo lists
- Filesystem access for saving/loading
- Subagent delegation
- Memory and persistence

Key concepts:
  - create_deep_agent() harness
  - Built-in filesystem tools
  - Planning with write_todos

Run this file (requires deepagents package):
  uv add deepagents
  uv run deep_research/summary_agents/stage_06_deep_agents/01_summary_deep_agent.py
"""

from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from langchain.tools import tool
from langchain_core.messages import HumanMessage

from deep_research.summary_agents.shared import load_transcript, format_transcript_for_llm


# ---------------------------------------------------------------------------
# Custom Tools for Summary Agent
# ---------------------------------------------------------------------------

@tool
def load_transcript_for_analysis(path: str) -> str:
    """
    Load a meeting transcript from the given path.
    Returns the formatted transcript text.
    """
    transcript = load_transcript(path)
    formatted = format_transcript_for_llm(transcript, format_type="speaker_turns")
    return f"""Transcript loaded:
- Duration: {transcript.duration:.1f}s
- Speakers: {', '.join(transcript.speakers)}
- Words: {transcript.total_words}

Content:
{formatted[:2000]}..."""


@tool
def extract_action_items_detailed(transcript_text: str) -> str:
    """
    Extract detailed action items from transcript.
    Returns structured action items with assignees.
    """
    # In production, would use LLM
    lines = transcript_text.split("\n")
    action_keywords = ["need to", "should", "will", "action", "todo", "follow up"]
    
    items = []
    for line in lines:
        if any(kw in line.lower() for kw in action_keywords):
            items.append(line.strip())
    
    if not items:
        return "No explicit action items found."
    
    return "Action Items:\n" + "\n".join(f"{i+1}. {item}" for i, item in enumerate(items[:5]))


@tool
def format_markdown_summary(
    title: str,
    overview: str,
    key_points: str,
    decisions: str,
    action_items: str,
    output_path: str = "/tmp/summary.md"
) -> str:
    """
    Format and save a markdown summary to the filesystem.
    Returns the path to the saved file.
    """
    summary = f"""# {title}

## Overview
{overview}

## Key Points
{key_points}

## Decisions
{decisions}

## Action Items
{action_items}

---
*Generated by Summary Deep Agent*
"""
    # Note: Deep Agent will use its built-in write_file
    return f"Summary formatted. Content:\n{summary}\n\n[Would save to: {output_path}]"


# ---------------------------------------------------------------------------
# Build Deep Agent
# ---------------------------------------------------------------------------

def build_summary_deep_agent():
    """Build the summary deep agent with all capabilities."""
    try:
        from deepagents import create_deep_agent
        from deepagents.backends import FilesystemBackend
        from langgraph.checkpoint.memory import MemorySaver
    except ImportError as e:
        raise RuntimeError(
            "deepagents is not installed. Run: uv add deepagents"
        ) from e
    
    from config import create_chat_model
    
    # Custom tools for summarization
    custom_tools = [
        load_transcript_for_analysis,
        extract_action_items_detailed,
        format_markdown_summary,
    ]
    
    model = create_chat_model(profile="asr_v2", temperature=0, max_tokens=1024)
    
    return create_deep_agent(
        name="meeting-summarizer",
        model=model,
        tools=custom_tools,
        system_prompt="""You are an expert meeting summarizer with access to:

1. Filesystem tools for reading/writing transcripts and summaries
2. Custom tools for transcript analysis and action item extraction
3. Todo tracking for complex multi-step summaries

Your workflow:
1. Plan your approach (write_todos)
2. Load the transcript
3. Extract key information (topics, decisions, action items)
4. Generate a formatted summary
5. Save the result to the filesystem

Always provide structured, professional summaries with clear sections.""",
        backend=FilesystemBackend(root_dir=str(REPO_ROOT), virtual_mode=True),
        checkpointer=MemorySaver(),
    )


# ---------------------------------------------------------------------------
# Demo (without running actual agent to avoid dependency)
# ---------------------------------------------------------------------------

print("=" * 70)
print("  STAGE 6.1: SUMMARY DEEP AGENT")
print("=" * 70)

print("""
This file demonstrates the Deep Agent pattern for meeting summarization.

DEEP AGENT CAPABILITIES:
━━━━━━━━━━━━━━━━━━━━━━━━

Built-in Tools:
  ✅ write_todos - Plan and track multi-step tasks
  ✅ ls, read_file, write_file - Filesystem access
  ✅ task - Delegate to specialized subagents

Custom Tools:
  📄 load_transcript_for_analysis - Load meeting transcripts
  ✅ extract_action_items_detailed - Find todos
  📝 format_markdown_summary - Create formatted output

Agent Configuration:
  - Name: meeting-summarizer
  - Model: asr_v2 profile
  - Backend: Filesystem (virtual mode)
  - Checkpointer: MemorySaver

USAGE:
------
```python
agent = build_summary_deep_agent()

result = agent.invoke({
    "messages": [{
        "role": "user",
        "content": "Summarize the meeting at /path/to/transcript.json"
    }]
}, config={"configurable": {"thread_id": "summary-001"}})
```

EXPECTED BEHAVIOR:
------------------
1. Agent creates todo list: [load, analyze, extract, format, save]
2. Loads transcript using custom tool
3. Extracts key information
4. Generates formatted markdown summary
5. Saves to filesystem via built-in write_file
6. Reports completion with file path

BENEFITS OVER STANDARD AGENTS:
-------------------------------
  - Built-in planning (no custom todo code needed)
  - Automatic filesystem access
  - Subagent delegation ready
  - Persistence with checkpointer
  - Structured task management
""")

# Show the agent structure without running
print("-" * 70)
print("  AGENT STRUCTURE")
print("-" * 70)
print("""
┌─────────────────────────────────────────────────────────────────────┐
│                    Summary Deep Agent                               │
├─────────────────────────────────────────────────────────────────────┤
│  System: Expert meeting summarizer with planning capabilities       │
├─────────────────────────────────────────────────────────────────────┤
│  Built-in Tools:                                                    │
│    • write_todos - Plan multi-step summary tasks                    │
│    • ls, read_file, write_file - Filesystem operations              │
│    • task - Delegate to subagents                                   │
├─────────────────────────────────────────────────────────────────────┤
│  Custom Tools:                                                      │
│    • load_transcript_for_analysis - Load and format transcripts     │
│    • extract_action_items_detailed - Extract todos                  │
│    • format_markdown_summary - Create formatted output              │
├─────────────────────────────────────────────────────────────────────┤
│  Backend: FilesystemBackend (virtual_mode=True)                     │
│  Checkpointer: MemorySaver                                           │
└─────────────────────────────────────────────────────────────────────┘
""")

print("-" * 70)
print("  SAMPLE WORKFLOW")
print("-" * 70)
print("""
User: "Summarize the meeting at /data/meeting.json"

Agent:
  1. write_todos: ["Load transcript", "Extract key points", 
                   "Find action items", "Generate summary", "Save to file"]
  
  2. load_transcript_for_analysis("/data/meeting.json")
     → Returns formatted transcript
  
  3. extract_action_items_detailed(transcript)
     → Returns structured action items
  
  4. format_markdown_summary(...)
     → Returns formatted summary
  
  5. write_file(path="/tmp/summary.md", content=summary)
     → Saves to filesystem
  
  6. Report: "Summary saved to /tmp/summary.md. 3 action items identified."
""")

print("\n" + "=" * 70)
print("  NEXT: Stage 6.2 → Subagent Swarm")
print("=" * 70)
