"""
Stage 2, File 1: ReAct Summary Agent
=====================================
CONCEPT: Agent that decides which summarization tools to use.

Instead of a single prompt, we give the agent specialized tools for
different aspects of summarization. The agent uses ReAct (Reasoning + Acting)
to decide which tools to call and in what order.

Key concepts:
  - @tool decorator for creating agent tools
  - create_agent() for ReAct agent
  - Agent decides tool sequence based on content

Run this file:
  uv run deep_research/summary_agents/stage_02_langchain_agents/01_react_summary_agent.py
"""

from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from langchain.tools import tool
from langchain.agents import create_tool_calling_agent, AgentExecutor
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

from config import create_chat_model
from deep_research.summary_agents.shared import load_transcript, format_transcript_for_llm


# ---------------------------------------------------------------------------
# Define Summarization Tools
# ---------------------------------------------------------------------------

@tool
def extract_action_items(transcript_text: str) -> str:
    """
    Extract action items, tasks, and todos from the transcript.
    Returns a list of action items with assignees if mentioned.
    """
    # In a real implementation, this might use a specialized model
    # For demo, we simulate with keyword detection
    action_keywords = ["need to", "should", "will", "let's", "action item", "todo", "follow up"]
    lines = transcript_text.split("\n")
    
    items = []
    for line in lines:
        lower = line.lower()
        if any(kw in lower for kw in action_keywords):
            items.append(line.strip())
    
    if not items:
        return "No explicit action items found in the transcript."
    
    return "Action Items Found:\n" + "\n".join(f"- {item}" for item in items[:5])


@tool
def extract_decisions(transcript_text: str) -> str:
    """
    Extract decisions made during the meeting.
    Returns a list of decisions with context.
    """
    decision_keywords = ["decided", "agreed", "will use", "going with", "consensus", "approve"]
    lines = transcript_text.split("\n")
    
    decisions = []
    for line in lines:
        lower = line.lower()
        if any(kw in lower for kw in decision_keywords):
            decisions.append(line.strip())
    
    if not decisions:
        return "No explicit decisions recorded in the transcript."
    
    return "Decisions Made:\n" + "\n".join(f"- {d}" for d in decisions[:5])


@tool
def identify_topics(transcript_text: str) -> str:
    """
    Identify main topics and themes discussed in the meeting.
    Returns a list of topics with brief descriptions.
    """
    # Simple keyword-based topic extraction for demo
    topics = []
    
    if "api" in transcript_text.lower():
        topics.append("API Integration - Discussion about API design or integration")
    if "jwt" in transcript_text.lower() or "auth" in transcript_text.lower():
        topics.append("Authentication - JWT or authentication mechanisms")
    if "wcag" in transcript_text.lower() or "accessibility" in transcript_text.lower():
        topics.append("Accessibility - WCAG compliance and accessibility features")
    if "node" in transcript_text.lower() or "backend" in transcript_text.lower():
        topics.append("Backend Technology - Node.js or backend architecture")
    if "roadmap" in transcript_text.lower() or "quarter" in transcript_text.lower():
        topics.append("Planning - Roadmap and quarterly planning")
    
    if not topics:
        return "General discussion - No specific technical topics identified"
    
    return "Topics Discussed:\n" + "\n".join(f"- {t}" for t in topics)


@tool
def format_final_summary(
    overview: str,
    topics: str,
    decisions: str,
    action_items: str
) -> str:
    """
    Combine all extracted information into a formatted summary.
    Returns a professional meeting summary document.
    """
    summary = f"""# Meeting Summary

## Overview
{overview}

## Topics Discussed
{topics}

## Decisions Made
{decisions}

## Action Items
{action_items}

---
*Generated by AI Summary Agent*
"""
    return summary


# ---------------------------------------------------------------------------
# Setup Agent
# ---------------------------------------------------------------------------

tools = [
    extract_action_items,
    extract_decisions,
    identify_topics,
    format_final_summary,
]

llm = create_chat_model(
    profile="asr_v2",
    temperature=0,
    max_tokens=2048,
)

# Create the agent with a system prompt
system_prompt = """You are a meeting summarization agent. Your job is to analyze meeting transcripts and create comprehensive summaries.

You have access to specialized tools for different aspects of summarization:
1. First, identify the main topics discussed
2. Extract any decisions that were made
3. Find action items and tasks assigned
4. Finally, format everything into a professional summary

Think step by step and use the tools as needed."""

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
    ("human", "{input}"),
])

agent = create_tool_calling_agent(llm, tools, prompt)
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,  # Show reasoning steps
    max_iterations=10,
)


# ---------------------------------------------------------------------------
# Run the Agent
# ---------------------------------------------------------------------------

transcript = load_transcript("deep_research/summary_agents/shared/sample_data/meeting_sample.json")
transcript_text = format_transcript_for_llm(transcript, format_type="speaker_turns")

print("=" * 70)
print("  STAGE 2.1: ReAct SUMMARY AGENT")
print("=" * 70)
print(f"\nTranscript: {len(transcript_text)} chars")
print("\nThe agent will decide which tools to use...\n")

# Truncate transcript for demo (agents can be verbose)
transcript_preview = transcript_text[:1500] + "\n...[truncated for demo]"

result = agent_executor.invoke({
    "input": f"Create a comprehensive summary of this meeting transcript:\n\n{transcript_preview}"
})

print("\n" + "=" * 70)
print("  FINAL OUTPUT")
print("=" * 70)
print(result["output"])


# ---------------------------------------------------------------------------
# Key Takeaways
# ---------------------------------------------------------------------------

print("\n" + "=" * 70)
print("  KEY TAKEAWAYS")
print("=" * 70)
print("""
✅ Agent decides which tools to use based on content
✅ Modular design: each tool handles one aspect
✅ ReAct loop shows reasoning (thought → action → observation)
✅ Easy to add new capabilities (new tools)

⚠️ Limitations:
   - Can get stuck in loops if tools are poorly designed
   - Each tool call is an LLM call = higher latency
   - Token usage adds up quickly with verbose reasoning
   - Limited state persistence between calls

Agent vs Direct Prompting:
   | Aspect         | Direct Prompt | Agent        |
   |----------------|---------------|--------------|
   | Control        | High          | Lower        |
   | Flexibility    | Low           | High         |
   | Cost           | Lower         | Higher       |
   | Debuggability  | Easy          | Harder       |

Next: Stage 2.2 → Multi-stage explicit pipeline
""")
